language: ruby
install: 
  - bundle install
  - npm install -g grunt-cli bower
  - npm install
before_script:
  - bundle exec rake test_server:build
  - bundle exec rake test_server:start_in_background
script: bundle exec rake overlay:test_both